# Generated by Django 4.2.30 on 2026-07-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('malaria', 'Malária'), ('colera', 'Cólera'), ('dengue', 'Dengue'), ('outra', 'Outra')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True, help_text='Lista de sintomas principais')),
                ('orientacao', models.TextField(blank=True, help_text='O que fazer')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Províncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('doses_recomendadas', models.PositiveIntegerField()),
                ('idade_minima', models.PositiveIntegerField(default=0, help_text='Idade mínima em meses')),
                ('idade_maxima', models.PositiveIntegerField(blank=True, help_text='Idade máxima em meses', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('ocupados', models.PositiveIntegerField()),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='saude.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('critico', 'Crítico'), ('atencao', 'Atenção'), ('informacao', 'Informação')], max_length=20)),
                ('status', models.CharField(default='Ativo', max_length=50)),
                ('orientacao', models.TextField(blank=True, help_text='Recomendações ou link')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='saude.doenca')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='saude.provincia')),
            ],
            options={
                'ordering': ['-gravidade', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CoberturaVacinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meta', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='saude.provincia')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='saude.vacina')),
            ],
            options={
                'ordering': ['-ano'],
                'unique_together': {('provincia', 'vacina', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='CasoDoenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('confirmados', models.PositiveIntegerField(default=0)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='saude.doenca')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='saude.provincia')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('provincia', 'doenca', 'data')},
            },
        ),
    ]
