# Generated by Django 4.2.30 on 2026-07-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alerta',
            table='alerta',
        ),
        migrations.AlterModelTable(
            name='casodoenca',
            table='caso_doenca',
        ),
        migrations.AlterModelTable(
            name='coberturavacinal',
            table='cobertura_vacinal',
        ),
        migrations.AlterModelTable(
            name='doenca',
            table='doenca',
        ),
        migrations.AlterModelTable(
            name='leito',
            table='leito',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='provincia',
        ),
        migrations.AlterModelTable(
            name='vacina',
            table='vacina',
        ),
    ]
