# Generated by Django 4.2.30 on 2026-07-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_alter_alerta_table_alter_casodoenca_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alerta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='casodoenca',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coberturavacinal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='doenca',
            table=None,
        ),
        migrations.AlterModelTable(
            name='leito',
            table=None,
        ),
        migrations.AlterModelTable(
            name='provincia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vacina',
            table=None,
        ),
    ]
