# Generated by Django 4.2.30 on 2026-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0004_alter_alerta_table_alter_casodoenca_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='orientacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='orientacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='sintomas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='idade_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='idade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
