# Generated by Django 4.2.30 on 2026-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0005_alter_alerta_orientacao_alter_doenca_orientacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='orientacao',
            field=models.TextField(blank=True, help_text='Recomendações ou link'),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='orientacao',
            field=models.TextField(blank=True, help_text='O que fazer'),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='sintomas',
            field=models.TextField(blank=True, help_text='Lista de sintomas principais'),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='idade_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='Idade máxima em meses', null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='idade_minima',
            field=models.PositiveIntegerField(default=0, help_text='Idade mínima em meses'),
        ),
    ]
