# Generated by Django 4.2.30 on 2026-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0006_alter_alerta_orientacao_alter_doenca_orientacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para identificação', max_length=100)),
                ('url', models.URLField(help_text='URL da API que retorna dados em JSON')),
                ('token', models.CharField(blank=True, help_text='Token de autenticação (Bearer)', max_length=255)),
                ('tipo_dado', models.CharField(choices=[('casos', 'Casos de Doenças'), ('alertas', 'Alertas'), ('cobertura', 'Cobertura Vacinal'), ('leitos', 'Leitos')], max_length=20)),
                ('intervalo', models.CharField(choices=[('1h', 'A cada 1 hora'), ('6h', 'A cada 6 horas'), ('12h', 'A cada 12 horas'), ('24h', 'Diariamente'), ('semanal', 'Semanalmente')], default='24h', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_status', models.CharField(blank=True, help_text='Status da última execução', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracao_api',
                'ordering': ['nome'],
            },
        ),
    ]
