# Generated by Django 6.0.6 on 2026-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0007_configuracaoapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodoenca',
            name='curados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='obitos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
