# Generated by Django 4.2.30 on 2026-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0008_casodoenca_curados_casodoenca_obitos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doenca',
            options={'verbose_name': 'Doença', 'verbose_name_plural': 'Doenças'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nome'], 'verbose_name': 'Província', 'verbose_name_plural': 'Províncias'},
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='casos_acumulados',
            field=models.PositiveIntegerField(default=0, help_text='Total acumulado desde o início'),
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='fonte',
            field=models.CharField(default='manual', help_text='Fonte dos dados (ex: WHO, MISAU, CSV)', max_length=100),
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='novos_casos',
            field=models.PositiveIntegerField(default=0, help_text='Novos casos no período'),
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='novos_obitos',
            field=models.PositiveIntegerField(default=0, help_text='Novos óbitos no período'),
        ),
        migrations.AddField(
            model_name='casodoenca',
            name='obitos_acumulados',
            field=models.PositiveIntegerField(default=0, help_text='Total de óbitos acumulados'),
        ),
        migrations.AlterField(
            model_name='casodoenca',
            name='data',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='casodoenca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracaoapi',
            name='tipo_dado',
            field=models.CharField(choices=[('casos', 'Casos de Doenças'), ('covid19', 'COVID-19'), ('alertas', 'Alertas'), ('cobertura', 'Cobertura Vacinal'), ('leitos', 'Leitos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='tipo',
            field=models.CharField(choices=[('malaria', 'Malária'), ('colera', 'Cólera'), ('dengue', 'Dengue'), ('covid19', 'COVID-19'), ('outra', 'Outra')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='casodoenca',
            index=models.Index(fields=['doenca', 'data'], name='caso_doenca_doenca__513944_idx'),
        ),
        migrations.AddIndex(
            model_name='casodoenca',
            index=models.Index(fields=['provincia', 'data'], name='caso_doenca_provinc_e425f0_idx'),
        ),
    ]
