# Generated by Django 4.2.30 on 2026-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0009_alter_doenca_options_alter_provincia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoapi',
            name='ultimo_status',
            field=models.CharField(blank=True, help_text='Status da última execução', max_length=500),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='tipo',
            field=models.CharField(choices=[('malaria', 'Malária'), ('colera', 'Cólera'), ('covid19', 'COVID-19'), ('outra', 'Outra')], max_length=20),
        ),
    ]
