# Generated by Django 4.2.30 on 2026-08-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0010_alter_configuracaoapi_ultimo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoapi',
            name='tipo_dado',
            field=models.CharField(choices=[('casos', 'Casos de Doenças'), ('covid19', 'COVID-19'), ('alertas', 'Alertas'), ('cobertura', 'Cobertura Vacinal'), ('leitos', 'Leitos'), ('clima', 'Dados Climáticos / Previsão do Tempo')], max_length=20),
        ),
        migrations.CreateModel(
            name='PrevisaoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('umidade', models.IntegerField(blank=True, null=True)),
                ('vento_velocidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicao', models.CharField(blank=True, max_length=100)),
                ('alerta_tempestade', models.BooleanField(default=False)),
                ('fonte', models.CharField(default='API', max_length=100)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='saude.provincia')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('provincia', 'data')},
            },
        ),
        migrations.CreateModel(
            name='DadosClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitacao', models.DecimalField(blank=True, decimal_places=2, help_text='Precipitação em mm', max_digits=8, null=True)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, help_text='Umidade relativa %', max_digits=5, null=True)),
                ('vento_velocidade', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidade do vento (km/h ou m/s)', max_digits=6, null=True)),
                ('tempestade', models.BooleanField(default=False, help_text='Indica se há previsão de tempestade')),
                ('descricao', models.CharField(blank=True, help_text="Descrição do tempo (ex: 'Céu limpo', 'Chuva forte')", max_length=200)),
                ('fonte', models.CharField(default='API', max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clima', to='saude.provincia')),
            ],
            options={
                'db_table': 'dados_clima',
                'ordering': ['-data'],
                'unique_together': {('provincia', 'data')},
            },
        ),
    ]
