# Generated by Django 4.2.30 on 2026-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0011_alter_configuracaoapi_tipo_dado_previsaotempo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoapi',
            name='tipo_dado',
            field=models.CharField(choices=[('casos', 'Casos de Doenças'), ('covid19', 'COVID-19'), ('alertas', 'Alertas'), ('cobertura', 'Cobertura Vacinal'), ('leitos', 'Leitos')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PrevisaoTempo',
        ),
    ]
