# Generated by Django 4.2.30 on 2026-09-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0012_alter_configuracaoapi_tipo_dado_delete_previsaotempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoapi',
            name='mapeamento',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento personalizado: {"data": "coluna_data", "novos_casos": "coluna_novos"}'),
        ),
    ]
